### PR TITLE
ARGS as option

### PR DESCRIPTION
**Pull request by urshofer**
added option args, falling back to default if not passed.

### CODE REVIEW

**Comment by saadq** [comment]
This is a good idea. Can you just update the docs in the README as well with the new option?

**Comment by urshofer** [comment]
fixed readme as well...

**Comment by saadq** [comment]
Merged, thanks very much for the contribution! :D

**Comment by urshofer** [comment]
Thanks for your work! I can use your script very well!

**Comment by saadq** [comment]
Glad to hear it :)

The package has been updated on `npm` as well under v2.5

**Pull request merged**
